name: vuzix_ultralite_flutter_plugin
description: Flutter plugin for Vuzix Ultralite SDK, enabling integration with Vuzix smart glasses for text display and device control.
version: 0.1.0
homepage: https://github.com/loitsut/vuzix_ultralite_flutter_plugin

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.loitsut.vuzix_ultralite_flutter_plugin
        pluginClass: VuzixUltralitePlugin
      ios:
        pluginClass: VuzixUltralitePlugin
